#!/bin/bash
# Deploy The Desk to Vercel (password-gated).
# Usage: ./deploy.sh            — copy fresh app files from review-app/ and deploy to prod.
# Fresh data first: python3 -m apply_assistant.cli export
set -euo pipefail
cd "$(dirname "$0")"

cp "../review-app/The Desk - Triage.dc.html" desk.html
cp ../review-app/support.js support.js

# desk-data.js is generated by `apply export`, which needs a candidate profile
# and scored jobs. On a first deploy neither exists yet — and with `set -e` a
# missing file would abort before anything ships. Stub an empty dataset instead
# so the site (and crucially /onboard) can go up BEFORE there is any data. The
# app pulls the real dataset from api/jobs at boot anyway.
if [ -f ../review-app/desk-data.js ]; then
  cp ../review-app/desk-data.js desk-data.js
else
  echo "  no desk-data.js yet — deploying with an empty dataset"
  cat > desk-data.js <<'EOF'
// Placeholder written by deploy.sh: no `apply export` has run yet.
// The live dataset is fetched from api/jobs at boot.
window.__DESK_DATA = [];
window.__DESK_RESUME = null;
window.__DESK_META = {};
window.__DESK_GENERATED = 0;
EOF
fi

# The remote onboarding form is GENERATED from apply_assistant/onboard.py, not
# kept as a second copy — the hosted form and the local one can never drift.
# Import the onboard module directly rather than going through the CLI: the CLI
# pulls in requests via sweep, which a bare system python3 won't have. This path
# is stdlib-only, so deploying never depends on the venv being active.
(cd .. && python3 -c \
  "from apply_assistant.onboard import emit_html; print('generated', emit_html('site/onboard.html'))")

# Pin to the job-desk project — a stale/missing .vercel link otherwise makes
# vercel auto-create a project named "site" (happened 2026-07-06) whose deploys
# never reach job-desk.vercel.app and lack the DESK_PASSWORD env.
vercel link --yes --project job-desk >/dev/null

vercel deploy --prod --yes
